# This is a basic workflow that is manually triggered

name: Manual build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      branch_name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Git branch name'
        # Default value if no value is explicitly provided
        default: 'develop'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  # This workflow contains a single job called "greet"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: echo "XXX ${{ github.event.inputs.branch_name }}."
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v2
        with:
          java-version: '13'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn build
